services:
  - type: web
    name: hackrx-llm-api
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install --no-cache-dir --prefer-binary -r requirements.txt
    startCommand: python main.py
    plan: free
    autoDeploy: false
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PORT
        value: "10000"
      - key: PYTHONPATH
        value: "."
      - key: PIP_PREFER_BINARY
        value: "1"
      - key: PIP_NO_BUILD_ISOLATION
        value: "false"
    healthCheckPath: /health
